### PR TITLE
Profile Updation with UserData

### LINKED ISSUE #3: Create a user profile page
You have to create a user profile page for this website. To achieve this, you can change the backend as well as the frontend without changing the current state of the website. The page should be accessible via all the private routes only.

The UI should match the current website's UI.

### PR DESCRIPTION
**Pull request by pooranjoyb**
### Changes
- [x] Additional data for User Profile added as requested.
- [x] New Session Data Updated.
- [x] Input separated for both Login and Signup.
- [x] Conditions applied making sure that current users not having the`New Data` won't crash the `Application`

### Description
Static Data fully converted to Fetched Data from the Database.

This PR merge fixes #3 

### Working Demo : 

[Video-Sun-Dec-10-2023-00-03-11.webm](https://github.com/Aditya61101/Group-Study/assets/90945182/00aff21c-fe3d-4fdd-8a37-0cb19d1075d0)

### Review and Merge this PR :) @Aditya61101

### CODE REVIEW

**Comment by pooranjoyb** [comment]
Here is the updated demonstration :)

[Video-Sun-Dec-10-2023-18-13-48.webm](https://github.com/Aditya61101/Group-Study/assets/90945182/917610f9-423f-4ea1-b88e-ab86e56b9f48)

@Aditya61101

**Comment by pooranjoyb** [comment]
### All your requested tasks are done :) @Aditya61101 

image

**Comment by Aditya61101** [comment]
> ### All your requested tasks are done :) @Aditya61101 
> 
> image
> 

You also made it responsive, right?

**Comment by pooranjoyb** [comment]
> 
> You also made it responsive, right?

Yep!

**Comment by Aditya61101** [comment]
Hey @pooranjoyb have you made changes in the login page as well?

**Comment by pooranjoyb** [comment]
> Hey @pooranjoyb have you made changes in the login page as well?

Some necessary changes I guess. 
Check [here](https://github.com/Aditya61101/Group-Study/commit/d38500e54833d5efd2ec1e75e04151845db6734c)

**Comment by Aditya61101** [comment]
> > Hey @pooranjoyb have you made changes in the login page as well?
> 
> Some necessary changes I guess. 
> Check [here](https://github.com/Aditya61101/Group-Study/commit/d38500e54833d5efd2ec1e75e04151845db6734c)

Those changes caused merge conflict😬

**Comment by pooranjoyb** [comment]
> > > Hey @pooranjoyb have you made changes in the login page as well?
> > 
> > 
> > Some necessary changes I guess.
> > Check [here](https://github.com/Aditya61101/Group-Study/commit/d38500e54833d5efd2ec1e75e04151845db6734c)
> 
> Those changes caused merge conflict😬

I did resolve all the conflicts. Please resolve and keep my changes wherever there's conflicts coz my changes are necessary for the functionalities that you've requested.

**Comment by Aditya61101** [comment]
> > > > Hey @pooranjoyb have you made changes in the login page as well?
> > > 
> > > 
> > > Some necessary changes I guess.
> > > Check [here](https://github.com/Aditya61101/Group-Study/commit/d38500e54833d5efd2ec1e75e04151845db6734c)
> > 
> > Those changes caused merge conflict😬
> 
> I did resolve all the conflicts. Please resolve and keep my changes wherever there's conflicts coz my changes are necessary for the functionalities that you've requested.

Can u try those functionalities now on the deployed one?

**Comment by pooranjoyb** [comment]
> Can u try those functionalities now on the deployed one?

Working fine on my side! 👍

**Comment by Aditya61101** [comment]
>  
> > Can u try those functionalities now on the deployed one?
> 
> Working fine on my side! 👍

Cool then

**Pull request merged**
