### PR TITLE
Make UI responsive

### LINKED ISSUE #14: fix: Fix mobile view of SignUp/Login/Create New Session page
## :question:  Problem description

- Forms are not responsive and are distorted in mobile view, making it not so user-friendly.

## :camera:  Screenshot

| Mobile View |
|---|
|Screenshot_2023-12-11-08-38-05-225_com android chrome|

## :framed_picture:  Proposed Solution

 - I wish to improve the responsiveness using Bootstrap and packages already used in the project. I can give the forms a more modern and appealing look for better user experience. 
 
## :page_with_curl:  Are you contributing for a program?

- I wish to contribute under <kbd> **CodePeak '23** </kbd>

Please do consider assigning me this task.

### PR DESCRIPTION
**Pull request by SamIsTheFBI**
**Closes #14**

## :memo: Description

- [x] Updated styles for Create Session/Edit Session forms.
- [x] Updated styles for Sign Up/Login page.

## :camera:  Screenshots

| Create Session| Login Screen |
|--------------------|---------------------------------------------------------------------------------------------------------------------------------------------------|
|image|image|image|

### CODE REVIEW

**Comment by Aditya61101** [comment]
@SamIsTheFBI the branch has some merge conflict, pls resolve it.

**Comment by Aditya61101** [comment]
@SamIsTheFBI pls do pull the changes from main branch before continuing your work. Are you able to resolve the conflict?

**Comment by SamIsTheFBI** [comment]
@Aditya61101 sure I can fix it, will add new commits soon.

By the way right now, the login page doesn't seem to work properly in the main branch. Could be from a recent PR merge into main branch.

**Comment by SamIsTheFBI** [comment]
Reopening this PR

**Comment by SamIsTheFBI** [comment]
Hey @Aditya61101 

Some recent changes in main branch have changed login/signup components and right now, login page is not working properly. I can't change responsiveness for these components until they're finalized. Please see to it.

And so, for the time being, I have committed the changes for create session page & edit session modal only.

**Comment by Aditya61101** [comment]
> Hey @Aditya61101 
> 
> Some recent changes in main branch have changed login/signup components and right now, login page is not working properly. I can't change responsiveness for these components until they're finalized. Please see to it.
> 
> And so, for the time being, I have committed the changes for create session page & edit session modal only. 

Ig the signup page is working fine, can u make it responsive? @SamIsTheFBI

**Comment by SamIsTheFBI** [comment]
> > Hey @Aditya61101
> > Some recent changes in main branch have changed login/signup components and right now, login page is not working properly. I can't change responsiveness for these components until they're finalized. Please see to it.
> > And so, for the time being, I have committed the changes for create session page & edit session modal only.
> 
> Ig the signup page is working fine, can u make it responsive? @SamIsTheFBI

Yes that can be fixed.

**Pull request merged**
