### PR TITLE
Logo Added to Navbar

### LINKED ISSUE #11: Study Planner Logo
Generally, every product / website has a really eye catching logo. Study Planner could lack proper promotion due to absence of a logo. I intend to use Adobe Illustrator to create an intricate logo for the website. If that's something you believe the website could benefit from, I would love to work on this issue

### PR DESCRIPTION
**Pull request by aindree-2005**
Screenshot (242)

-Created Light and Regular Version of Logo
-Changed logo on navbar
-Changed icon on tab
closes #11 
@Aditya61101 here's the changes with the screenshot

### CODE REVIEW

**Comment by Aditya61101** [comment]
> Screenshot (242)
> 
> -Created Light and Regular Version of Logo -Changed logo on navbar -Changed icon on tab closes #11 @Aditya61101 here's the changes with the screenshot

ig the navbar has been stretched a bit more. can you replace the logo with a one of smaller size? @aindree-2005

**Comment by aindree-2005** [comment]
Screenshot (245)

@Aditya61101 fixed it ! I feel like if I made the navbar less stretched out than this, logo would be invisible. So, reduced height, weight considerably. And added text beside instead of below

**Comment by Aditya61101** [comment]
> 
> Screenshot (245)
> 
> @Aditya61101 fixed it ! I feel like if I made the navbar less stretched out than this, logo would be invisible. So, reduced height, weight considerably. And added text beside instead of below

I still feel the navbar width is much larger. Consider fixing it also do check the responsiveness of the navbar on different devices.

**Comment by aindree-2005** [comment]
> > Screenshot (245)
> > @Aditya61101 fixed it ! I feel like if I made the navbar less stretched out than this, logo would be invisible. So, reduced height, weight considerably. And added text beside instead of below
> 
> I still feel the navbar width is much larger. Consider fixing it also do check the responsiveness of the navbar on different devices.

Ok then I am changing logo font so that it's bolder and visible in small size too. And making a new branch

**Comment by aindree-2005** [comment]
@Aditya61101 This PR is shifted to PR #15

**Pull request closed without merging**
