### PR TITLE
implemented comfirm password in sign up form

### PR DESCRIPTION
**Pull request by NandishM0618**
issue27
issue28
issue30
please merge it if you like and update my points thank you.

### CODE REVIEW

**Comment by Aditya61101** [comment]
Hey @NandishM0618 the login page doesn't work properly after your branch was merged. Is this the issue from your side?

**Comment by NandishM0618** [comment]
@Aditya61101 it was working fine. I willl send video of working.

**Comment by Aditya61101** [comment]
> @Aditya61101 it was working fine. I willl send video of working. 

After merging you can see the login page isn't showing the form on the main website, right ?

**Comment by NandishM0618** [comment]
Oh ok let me see to this and will update you. How about that?

**Comment by Aditya61101** [comment]
> Oh ok let me see to this and will update you. How about that? 

Yeah sure but pls do it asap, cz it has also halted other contributors.

**Comment by NandishM0618** [comment]
issue34
issue35
as you can see it's working fine with the same branch.

**Comment by Aditya61101** [comment]
> issue34
> issue35
> as you can see it's working fine with the same branch.

Have you pull the changes ? Try it on the official website @NandishM0618

**Comment by NandishM0618** [comment]
Hey @Aditya61101 did you assign someone for some feature implementation in sign up form. Cause there are two login form in code this might caused the issue.

**Comment by NandishM0618** [comment]
issue45
issue46
I have implemented LoginForm.js but I don't know someone might have changed the code and made it as RegisterLogin.js this caused the problem. please see to that and if any issues you are facing please update me.

**Comment by Aditya61101** [comment]
> issue45
> issue46
> I have implemented LoginForm.js but I don't know someone might have changed the code and made it as RegisterLogin.js this caused the problem. please see to that and if any issues you are facing please update me.

Yeah I have asked the contributor to look into the matter.

**Comment by Aditya61101** [comment]
Hey @NandishM0618 can u take the pull now from the main branch and do your changes again?

**Comment by NandishM0618** [comment]
Okay

**Comment by NandishM0618** [comment]
@Aditya61101 do you want me to change the signup form to original one or it should have name, age etc and all that?

**Comment by Aditya61101** [comment]
> @Aditya61101 do you want me to change the signup form to original one or it should have name, age etc and all that? 

It should have Name, age etc. Just add another field confirm Password.

**Pull request merged**
