### PR TITLE
dark mode first commit

### PR DESCRIPTION
**Pull request by Albert-2**
hey @Aditya61101 
I've done what you asked for

### CODE REVIEW

**Comment by Aditya61101** [comment]
> hey @Aditya61101 I've done what you asked for

pls provide a video demo or screenshot before I accept your PR. Also if you have used .env values, pls use it in a .env.local file.

**Comment by Aditya61101** [comment]
image

@Albert-2 that is a .env.example it will only have key not the original values, pls remove the values.

**Comment by Albert-2** [comment]
image
image
image
image
image

**Comment by Albert-2** [comment]
and removed the values too 
please review it 
sorry for inconvenience
Thank you for considering

**Comment by Aditya61101** [comment]
Ig it's too much black, consider using other shade of black.

**Comment by Aditya61101** [comment]
Also take the pull from main branch before working ahead. There are lots of changes. @Albert-2

**Comment by Albert-2** [comment]
okok
I'll update my main branch

**Comment by Albert-2** [comment]
image

is this shade is fine...?

**Comment by Albert-2** [comment]
@Aditya61101
The above shade of black is good or not .....??

**Comment by Aditya61101** [comment]
@Albert-2 ig we should stick with the light mode only.

**Comment by Albert-2** [comment]
@Aditya61101 
You don't like the color(I can change if you suggest any) or you don't want dark mode anyways

**Comment by Aditya61101** [comment]
I think we should leave it as it is.

**Comment by Albert-2** [comment]
hey @Aditya61101 
sorry i am not being greedy here but 
Will I receive any points for codepeak'23

**Comment by Aditya61101** [comment]
Sorry @Albert-2 , I really respect your effort, but I don't think they will give you any points.

**Pull request closed without merging**
